name: Kits
version: 1.1
api-version: 1.20
main: com.daemonresolve.mc.Kits
author: jason szot
description: simple kits plugin

commands:
  kit:
    usage: /<command> kit number
    description: gives you a kit
  listkits:
    usage: /<command>
    description: lists available kits