name: Kits
version: 1.1
api-version: 1.20
main: com.daemonresolve.mc.Kits
author: jason szot
description: simple kits plugin

commands:
  kit:
    usage: /<command>
    aliases: [kits]
    description: Opens the kits menu